---
- name: Install Docker and add jenkins user to docker group
  hosts: localhost
  become: true

  tasks:
    - name: Update server OS packages
      command: dnf update -y

    - name: Add signing key
      rpm_key:
        key: "https://download.docker.com/linux/rhel/gpg"
        state: present

    - name: Add repository into repo.d list
      yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/centos/9/x86_64/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/rhel/gpg"

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
        state: latest
        update_cache: true

    - name: Start Docker
      service:
        name: "docker"
        enabled: true
        state: started

    - name: Add Jenkins to Docker group
      user:
        name: "jenkins"
        groups: docker
        append: yes
